### ISSUE TITLE
sorry, icinga.icinga2 was not found on https://galaxy.ansible.com

### ISSUE THREAD

**Issue by slalomsk8er** [Icinga/ansible-icinga2#29]
I tried to install this ansible role but the command:

`ansible-galaxy install icinga.icinga2`

failed with the message:

`- downloading role 'icinga2', owned by icinga
 [WARNING]: - icinga.icinga2 was NOT installed successfully: - sorry, icinga.icinga2 was not found on https://galaxy.ansible.com.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.`

**Comment by slalomsk8er** [comment]
a workaround:
`ansible-galaxy install https://github.com/Icinga/ansible-icinga2/archive/v0.2.0.tar.gz`

**Comment by bobapple** [comment]
The role is not uploaded on Ansible Galaxy yet, since it's still in a very early version

**Comment by slalomsk8er** [comment]
It's a bug in the README.md then?

**Comment by RossBarnie** [comment]
Yes, we should probably make it clear that this role is still in development and not available on Galaxy at the moment.

**Comment by TinajaLabs** [comment]
Sadly, the readme still has a bug...  ;)

**Comment by aflatto** [comment]
Misleading line was removed from readme

**Comment by ltalirz** [comment]
If the misleading line was removed from the readme, then it has been reintroduced:


![image](https://user-images.githubusercontent.com/1053245/102620488-5da7fc00-413e-11eb-82d0-726c43b6c1ff.png)

**Comment by ltalirz** [comment]
P.S. 

> The role is not uploaded on Ansible Galaxy yet, since it's still in a very early version

Is this still the status quo?
Perfection is hard to achieve, but as soon as you would feel comfortable recommending to use this ansible role over the ~40 other "icinga2" roles one currently finds on ansible galaxy, I think it would make sense to release it.

If the issue is just the time to add the deployment, I'm sure many people would be happy to make a PR.

I see you're using molecule for testing; I can add automatic tests on Github Actions, if that would make you feel safer about releasing the role.
